/* eslint-disable @typescript-eslint/no-require-imports */
const { mkdirSync } = require("node:fs");
const path = require("node:path");
const { DatabaseSync } = require("node:sqlite");

const dbPath = path.join(process.cwd(), "prisma", "dev.db");
mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new DatabaseSync(dbPath);
db.exec(`
  PRAGMA foreign_keys = ON;
  CREATE TABLE IF NOT EXISTS locations (id TEXT PRIMARY KEY, state TEXT NOT NULL, municipality TEXT NOT NULL, district TEXT NOT NULL, UNIQUE(state, municipality, district));
  CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL, summary TEXT NOT NULL, capabilities TEXT NOT NULL, organization_kind TEXT, operating_area TEXT, is_demo INTEGER NOT NULL DEFAULT 1, location_id TEXT NOT NULL REFERENCES locations(id), can_supply_public INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS formal_opportunities (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, organization_id TEXT NOT NULL REFERENCES profiles(id), location_id TEXT NOT NULL REFERENCES locations(id), status TEXT NOT NULL DEFAULT 'OPEN', employment_type TEXT NOT NULL DEFAULT 'CLT');
  CREATE TABLE IF NOT EXISTS service_offers (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, provider_id TEXT NOT NULL REFERENCES profiles(id), location_id TEXT NOT NULL REFERENCES locations(id), availability TEXT NOT NULL, required_activities TEXT NOT NULL DEFAULT '');
  CREATE TABLE IF NOT EXISTS volunteer_opportunities (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, organizer_id TEXT NOT NULL REFERENCES profiles(id), location_id TEXT NOT NULL REFERENCES locations(id), schedule TEXT NOT NULL, event_date TEXT, requirements TEXT NOT NULL DEFAULT '', desired_volunteers INTEGER, institutional_guidance TEXT NOT NULL DEFAULT '');
  CREATE TABLE IF NOT EXISTS volunteer_participants (id TEXT PRIMARY KEY, opportunity_id TEXT NOT NULL REFERENCES volunteer_opportunities(id) ON DELETE CASCADE, person_profile_id TEXT NOT NULL REFERENCES profiles(id), status TEXT NOT NULL DEFAULT 'INTERESTED', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, confirmed_at TEXT, participated_at TEXT, UNIQUE(opportunity_id, person_profile_id));
  CREATE TABLE IF NOT EXISTS interactions (id TEXT PRIMARY KEY, actor_profile_id TEXT NOT NULL REFERENCES profiles(id), target_type TEXT NOT NULL, target_id TEXT NOT NULL, action TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(actor_profile_id, target_type, target_id));
  CREATE TABLE IF NOT EXISTS service_calls (id TEXT PRIMARY KEY, requester_profile_id TEXT NOT NULL REFERENCES profiles(id), title TEXT NOT NULL, activity TEXT NOT NULL, description TEXT NOT NULL, location_id TEXT NOT NULL REFERENCES locations(id), service_day TEXT NOT NULL, time_window TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'OPEN', accepted_by_profile_id TEXT REFERENCES profiles(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, accepted_at TEXT);
`);
try { db.exec("ALTER TABLE formal_opportunities ADD COLUMN employment_type TEXT NOT NULL DEFAULT 'CLT'"); } catch {}
try { db.exec("ALTER TABLE service_offers ADD COLUMN required_activities TEXT NOT NULL DEFAULT ''"); } catch {}
try { db.exec("ALTER TABLE volunteer_opportunities ADD COLUMN event_date TEXT"); } catch {}
try { db.exec("ALTER TABLE profiles ADD COLUMN can_supply_public INTEGER NOT NULL DEFAULT 0"); } catch {}
try { db.exec("ALTER TABLE profiles ADD COLUMN organization_kind TEXT"); } catch {}
try { db.exec("ALTER TABLE profiles ADD COLUMN operating_area TEXT"); } catch {}
try { db.exec("ALTER TABLE volunteer_opportunities ADD COLUMN requirements TEXT NOT NULL DEFAULT ''"); } catch {}
try { db.exec("ALTER TABLE volunteer_opportunities ADD COLUMN desired_volunteers INTEGER"); } catch {}
try { db.exec("ALTER TABLE volunteer_opportunities ADD COLUMN institutional_guidance TEXT NOT NULL DEFAULT ''"); } catch {}
db.prepare("UPDATE profiles SET can_supply_public = 1 WHERE id = 'profile-coletivo'").run();
db.exec("DELETE FROM service_calls; DELETE FROM interactions; DELETE FROM volunteer_participants; DELETE FROM formal_opportunities; DELETE FROM service_offers; DELETE FROM volunteer_opportunities; DELETE FROM profiles; DELETE FROM locations;");
const insert = (sql, ...params) => db.prepare(sql).run(...params);
const locations = [["loc-aracaju-centro", "SE", "Aracaju", "Centro"], ["loc-aracaju-bugio", "SE", "Aracaju", "Bugio"], ["loc-aracaju-sao-jose", "SE", "Aracaju", "São José"], ["loc-lagarto-centro", "SE", "Lagarto", "Centro"], ["loc-lagarto-cidade-nova", "SE", "Lagarto", "Cidade Nova"], ["loc-socorro-taicoca", "SE", "Nossa Senhora do Socorro", "Taiçoca"]];
for (const row of locations) insert("INSERT INTO locations (id, state, municipality, district) VALUES (?, ?, ?, ?)", ...row);
const profiles = [["profile-ana", "Hugo Silva", "PERSON", "Pessoa em busca de oportunidades e conexões locais.", "Candidato formal · Voluntário", "", "", "loc-aracaju-centro", "0"], ["profile-coletivo", "Coletivo Horizonte (demonstração)", "ORGANIZATION", "Empresa fictícia para demonstrar publicação de trabalho e serviços.", "Empresa · Ações comunitárias", "COMPANY", "Aracaju e municípios próximos", "loc-aracaju-sao-jose", "1"], ["profile-instituto", "Instituto Ponte Aberta (demonstração)", "ORGANIZATION", "ONG / OSC fictícia com atuação em desenvolvimento territorial.", "Voluntariado · Desenvolvimento local", "NONPROFIT", "Lagarto e comunidades parceiras", "loc-lagarto-cidade-nova", "0"], ["profile-instituicao-publica", "Secretaria Demo de Cidadania (fictícia)", "ORGANIZATION", "Instituição pública fictícia para demonstrar ações voluntárias de interesse coletivo.", "Ações voluntárias · Gestão de participantes", "PUBLIC_INSTITUTION", "Aracaju e equipamentos públicos parceiros", "loc-aracaju-centro", "0"], ["profile-rafael", "Amanda Figueiredo (demonstração)", "PERSON", "Profissional autônoma que atende demandas residenciais.", "Manutenção residencial · Serviços autônomos", "", "", "loc-lagarto-centro", "0"], ["profile-analista", "Observatório Território Aberto (demonstração)", "INSTITUTIONAL_ANALYST", "Persona fictícia para leitura agregada do território.", "Inteligência territorial · Análise agregada", "", "", "loc-aracaju-centro", "0"]];
for (const row of profiles) insert("INSERT INTO profiles (id, name, type, summary, capabilities, organization_kind, operating_area, location_id, can_supply_public) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", ...row);
insert("INSERT INTO formal_opportunities (id, title, description, category, organization_id, location_id, employment_type) VALUES (?, ?, ?, ?, ?, ?, ?)", "formal-operations", "Assistente de operações locais", "A pessoa apoiará a organização de rotas, conferência de estoque, contato com parceiros e registro de indicadores simples da operação. A rotina combina trabalho em equipe, acompanhamento de prazos e presença no território.", "Operações", "profile-coletivo", "loc-aracaju-centro", "CLT");
insert("INSERT INTO formal_opportunities (id, title, description, category, organization_id, location_id, employment_type) VALUES (?, ?, ?, ?, ?, ?, ?)", "formal-attendance", "Técnico de atendimento", "Atendimento presencial e remoto para uma rede de serviços em expansão, com acolhimento de solicitações, organização de agenda e encaminhamento para as áreas responsáveis. Buscamos comunicação clara e escuta ativa.", "Atendimento", "profile-coletivo", "loc-socorro-taicoca", "CLT");
insert("INSERT INTO formal_opportunities (id, title, description, category, organization_id, location_id, employment_type) VALUES (?, ?, ?, ?, ?, ?, ?)", "formal-logistics", "Auxiliar de logística comunitária", "Apoio ao recebimento de materiais, separação de pedidos, inventário e planejamento de entregas para iniciativas locais. A oportunidade é indicada para quem gosta de organização, rotina operacional e contato com diferentes bairros.", "Logística", "profile-coletivo", "loc-lagarto-centro", "CLT");
insert("INSERT INTO formal_opportunities (id, title, description, category, organization_id, location_id, employment_type) VALUES (?, ?, ?, ?, ?, ?, ?)", "formal-communications-intern", "Estágio em comunicação territorial", "Apoio à produção de textos, calendário editorial, registros de ações e organização de informações para redes sociais. O estágio oferece acompanhamento de uma pessoa responsável e espaço para desenvolver portfólio.", "Comunicação", "profile-coletivo", "loc-aracaju-sao-jose", "INTERNSHIP");
insert("INSERT INTO formal_opportunities (id, title, description, category, organization_id, location_id, employment_type) VALUES (?, ?, ?, ?, ?, ?, ?)", "formal-education-intern", "Estágio em projetos educativos", "Apoio ao planejamento de oficinas, preparação de materiais e acompanhamento de atividades com crianças e adolescentes. É uma oportunidade para quem estuda pedagogia, licenciaturas ou áreas relacionadas e quer aprender com uma equipe comunitária.", "Educação", "profile-instituto", "loc-lagarto-cidade-nova", "INTERNSHIP");
insert("INSERT INTO service_offers (id, title, description, category, provider_id, location_id, availability, required_activities) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "service-maintenance", "Manutenção residencial", "Atendimento para pequenos reparos elétricos, hidráulicos, instalação de suportes e ajustes de rotina em residências. O serviço começa com uma conversa sobre a demanda, avaliação do local e combinação transparente de prazo e materiais.", "Manutenção", "profile-rafael", "loc-lagarto-centro", "Agenda combinada pelo território", "Manutenção|Eletricista");
insert("INSERT INTO service_offers (id, title, description, category, provider_id, location_id, availability, required_activities) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "service-design", "Design e conteúdo local", "Criação de identidade visual simples, peças digitais, cardápios e textos para pequenos negócios e iniciativas locais. O trabalho inclui briefing, primeira proposta e rodada combinada de ajustes.", "Comunicação", "profile-coletivo", "loc-aracaju-sao-jose", "Atendimento remoto ou em Aracaju", "Design|Comunicação");
insert("INSERT INTO service_offers (id, title, description, category, provider_id, location_id, availability, required_activities) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "service-electrical", "Instalações elétricas residenciais", "Serviço de manutenção preventiva, troca de tomadas e interruptores, instalação de luminárias e identificação de pequenos problemas elétricos. O atendimento é combinado conforme o bairro e a complexidade da demanda.", "Eletricista", "profile-rafael", "loc-aracaju-centro", "Segunda a sexta, com horário combinado", "Eletricista|Manutenção");
insert("INSERT INTO service_offers (id, title, description, category, provider_id, location_id, availability, required_activities) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "service-food", "Alimentação para eventos locais", "Planejamento e produção de lanches, coffee breaks e refeições para encontros de pequeno e médio porte. A proposta considera quantidade de pessoas, restrições informadas e logística de entrega.", "Alimentação", "profile-rafael", "loc-socorro-taicoca", "Reservas com antecedência", "Alimentação|Eventos");
insert("INSERT INTO service_offers (id, title, description, category, provider_id, location_id, availability, required_activities) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "service-tutoring", "Aulas de reforço escolar", "Acompanhamento individual ou em pequenos grupos para organização de estudos, leitura e matemática. O plano é ajustado à idade, ao objetivo da família e à rotina disponível.", "Educação", "profile-coletivo", "loc-aracaju-bugio", "Tardes e início da noite", "Educação|Cuidados");
insert("INSERT INTO volunteer_opportunities (id, title, description, category, organizer_id, location_id, schedule, event_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "volunteer-reading", "Mutirão de leitura comunitária", "Encontros de leitura para crianças e adolescentes em um espaço comunitário do bairro, com preparação de atividades, acolhimento das famílias e registro das histórias compartilhadas. Não é necessário ter experiência prévia: a equipe orienta as pessoas voluntárias.", "Educação", "profile-instituto", "loc-aracaju-bugio", "Sábados, pela manhã", "2026-10-03T09:00:00-03:00");
insert("INSERT INTO volunteer_opportunities (id, title, description, category, organizer_id, location_id, schedule, event_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "volunteer-health", "Apoio à feira de saúde", "Recepção, organização de fluxo e apoio à comunicação em uma ação comunitária de orientação e prevenção. A pessoa voluntária recebe um roteiro de atividades e atua sempre junto da equipe responsável pela feira.", "Saúde", "profile-instituto", "loc-lagarto-cidade-nova", "Uma manhã, com escala prévia", "2026-10-10T08:00:00-03:00");
insert("INSERT INTO volunteer_opportunities (id, title, description, category, organizer_id, location_id, schedule, event_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "volunteer-park", "Cuidado coletivo da praça", "Mobilização para limpeza leve, plantio de mudas e pintura de sinalização em uma praça do bairro. A iniciativa oferece materiais, divisão de tarefas e uma conversa final sobre manutenção do espaço comum.", "Meio ambiente", "profile-instituto", "loc-aracaju-sao-jose", "Domingo, das 8h às 11h", "2026-10-18T08:00:00-03:00");
insert("INSERT INTO volunteer_opportunities (id, title, description, category, organizer_id, location_id, schedule, event_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", "volunteer-digital", "Oficina de inclusão digital", "Apoio a pessoas idosas durante uma oficina prática sobre celular, serviços públicos digitais e segurança básica. É possível atuar no acolhimento, na orientação individual ou na organização do espaço.", "Inclusão digital", "profile-instituto", "loc-lagarto-centro", "Quartas-feiras, no fim da tarde", "2026-10-21T17:30:00-03:00");
insert("INSERT INTO volunteer_opportunities (id, title, description, category, organizer_id, location_id, schedule, event_date, requirements, desired_volunteers, institutional_guidance) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", "volunteer-public-citizenship", "Apoio ao mutirão de cidadania", "Ação voluntária fictícia de apoio à orientação de moradores sobre serviços públicos, acolhimento e organização do fluxo no equipamento público.", "Direitos e cidadania", "profile-instituicao-publica", "loc-aracaju-centro", "Uma manhã, com escala prévia", "2026-11-07T08:00:00-03:00", "Escuta respeitosa, pontualidade e disponibilidade para seguir a orientação da equipe.", "8", "A ação é gratuita, não substitui atendimento público e será acompanhada por servidoras e servidores responsáveis.");
insert("INSERT INTO interactions (id, actor_profile_id, target_type, target_id, action) VALUES (?, ?, ?, ?, ?)", "interaction-demo-1", "profile-ana", "FORMAL", "formal-operations", "APPLY");
insert("INSERT INTO interactions (id, actor_profile_id, target_type, target_id, action) VALUES (?, ?, ?, ?, ?)", "interaction-demo-2", "profile-ana", "VOLUNTEER", "volunteer-reading", "VOLUNTEER_INTEREST");
insert("INSERT INTO interactions (id, actor_profile_id, target_type, target_id, action) VALUES (?, ?, ?, ?, ?)", "interaction-demo-3", "profile-rafael", "SERVICE", "service-design", "CONTACT_REQUEST");
insert("INSERT INTO interactions (id, actor_profile_id, target_type, target_id, action) VALUES (?, ?, ?, ?, ?)", "interaction-demo-4", "profile-ana", "SERVICE", "service-maintenance", "CONTACT_REQUEST");
insert("INSERT INTO volunteer_participants (id, opportunity_id, person_profile_id, status) VALUES (?, ?, ?, ?)", "volunteer-participation-demo-1", "volunteer-reading", "profile-ana", "INTERESTED");
console.log("Seed concluído: 6 territórios, 6 perfis, 15 oportunidades e 4 interações DEMO DATA.");
