import type { FormalEmploymentType } from "@/lib/db";

type Point = { municipality: string; district: string; employmentType: FormalEmploymentType; total: number };

export function RegionalEmploymentChart({ points }: { points: Point[] }) {
  const regions = Array.from(new Map(points.map((point) => [`${point.municipality}-${point.district}`, { municipality: point.municipality, district: point.district }])).values());
  const max = Math.max(1, ...regions.map((region) => points.filter((point) => point.municipality === region.municipality && point.district === region.district).reduce((total, point) => total + point.total, 0)));
  function totalFor(region: { municipality: string; district: string }, type: FormalEmploymentType) { return points.find((point) => point.municipality === region.municipality && point.district === region.district && point.employmentType === type)?.total ?? 0; }
  return <section className="panel mt-8 p-6 sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="eyebrow">Empregos na região</p><h2 className="mt-2 text-xl font-bold text-navy">Distribuição de vagas CLT e estágio</h2><p className="mt-2 text-sm leading-6 text-[#687b8b]">Quantidade de oportunidades formais abertas por município e região da base demo.</p></div><div className="flex gap-4 text-xs font-bold text-[#637688]"><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-blue" />CLT</span><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-[#86b8c8]" />Estágio</span></div></div><div className="mt-7 space-y-5">{regions.map((region) => { const clt = totalFor(region, "CLT"); const internship = totalFor(region, "INTERNSHIP"); return <div key={`${region.municipality}-${region.district}`}><div className="mb-2 flex justify-between gap-4 text-sm"><span className="font-bold text-navy">{region.municipality} · {region.district}</span><span className="font-bold text-blue">{clt + internship}</span></div><div className="flex h-3 overflow-hidden rounded-full bg-[#e5edf2]"><div className="bg-blue" style={{ width: `${(clt / max) * 100}%` }} title={`${clt} CLT`} /><div className="bg-[#86b8c8]" style={{ width: `${(internship / max) * 100}%` }} title={`${internship} estágio`} /></div><div className="mt-1 flex gap-4 text-xs text-[#738593]"><span>{clt} CLT</span><span>{internship} estágio</span></div></div>; })}</div></section>;
}
