"use client";

import { Bell, CalendarPlus, Check } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

export function VolunteerReminder({ opportunityId, title, description, schedule, eventDate, location }: { opportunityId: string; title: string; description: string; schedule: string; eventDate?: string; location: string }) {
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { setSaved((JSON.parse(window.localStorage.getItem("oflix-volunteer-reminders") ?? "[]") as string[]).includes(opportunityId)); } catch { /* estado inicial */ } }, [opportunityId]);
  const calendarUrl = useMemo(() => { const start = eventDate ? new Date(eventDate) : new Date("2026-10-03T09:00:00-03:00"); const end = new Date(start.getTime() + 2 * 60 * 60 * 1000); const format = (date: Date) => date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${format(start)}/${format(end)}&details=${encodeURIComponent(description)}&location=${encodeURIComponent(location)}`; }, [description, eventDate, location, title]);
  async function saveReminder() { if (typeof Notification !== "undefined" && Notification.permission === "default") await Notification.requestPermission(); const stored = JSON.parse(window.localStorage.getItem("oflix-volunteer-reminders") ?? "[]") as string[]; if (!stored.includes(opportunityId)) window.localStorage.setItem("oflix-volunteer-reminders", JSON.stringify([...stored, opportunityId])); setSaved(true); if (typeof Notification !== "undefined" && Notification.permission === "granted") new Notification("Lembrete salvo no OFLIX", { body: `${title} · ${schedule}` }); }
  return <div className="mt-6 rounded-lg border border-[#cbdde8] bg-[#f4f9fc] p-4"><p className="text-sm font-bold text-navy">Não perca o dia da ação</p><p className="mt-1 text-sm leading-6 text-[#637688]">Salve um lembrete no navegador ou adicione o encontro à sua agenda.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button type="button" className="button-primary" onClick={saveReminder}>{saved ? <Check size={16} /> : <Bell size={16} />}{saved ? "Lembrete salvo" : "Lembrar-me"}</button><a className="button-secondary" href={calendarUrl} target="_blank" rel="noreferrer"><CalendarPlus size={16} /> Adicionar ao Google Agenda</a></div><p className="mt-3 text-xs leading-5 text-[#718291]">O Google Agenda abrirá uma janela para você confirmar o evento. A notificação futura depende das permissões do seu navegador.</p></div>;
}
